apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: alaa228/url-shortener
          ports:
            - containerPort: 8080
          env:
            - name: DOCKER_ENV
              value: "true"
          envFrom:
            - secretRef:
                name: url-shortener-env
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
